version: '3.5'
services:

  frontend-start:
    container_name: frontend-start
    image: frontend-locapy:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm start
    volumes:
      - .:/front
    ports:
      - 3000:3000
    networks:
      - frontend

  frontend-install:
    container_name: frontend-install
    image: frontend-locapy:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm install --production
    volumes:
      - .:/front
    depends_on:
      - frontend-start
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
