version: '3.5'
services:

  frontend:
    container_name: frontend-locapy
    image: frontend-locapy:develop
    build:
      context: .
      dockerfile: Dockerfile-dev
    command: npm start
    volumes:
      - .:/front
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend:
    external:
      name: frontend
